package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class AcAccessRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_record.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_record.access_card_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer accessCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_record.public_access_control_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer publicAccessControlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_record.room_access_control_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer roomAccessControlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_record.operate_type
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_record.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_access_record
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_record.id
     *
     * @return the value of ac_access_record.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_record.id
     *
     * @param id the value for ac_access_record.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_record.access_card_id
     *
     * @return the value of ac_access_record.access_card_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getAccessCardId() {
        return accessCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_record.access_card_id
     *
     * @param accessCardId the value for ac_access_record.access_card_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setAccessCardId(Integer accessCardId) {
        this.accessCardId = accessCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_record.public_access_control_id
     *
     * @return the value of ac_access_record.public_access_control_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getPublicAccessControlId() {
        return publicAccessControlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_record.public_access_control_id
     *
     * @param publicAccessControlId the value for ac_access_record.public_access_control_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setPublicAccessControlId(Integer publicAccessControlId) {
        this.publicAccessControlId = publicAccessControlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_record.room_access_control_id
     *
     * @return the value of ac_access_record.room_access_control_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getRoomAccessControlId() {
        return roomAccessControlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_record.room_access_control_id
     *
     * @param roomAccessControlId the value for ac_access_record.room_access_control_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRoomAccessControlId(Integer roomAccessControlId) {
        this.roomAccessControlId = roomAccessControlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_record.operate_type
     *
     * @return the value of ac_access_record.operate_type
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_record.operate_type
     *
     * @param operateType the value for ac_access_record.operate_type
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setOperateType(Byte operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_record.create_time
     *
     * @return the value of ac_access_record.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_record.create_time
     *
     * @param createTime the value for ac_access_record.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_record
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accessCardId=").append(accessCardId);
        sb.append(", publicAccessControlId=").append(publicAccessControlId);
        sb.append(", roomAccessControlId=").append(roomAccessControlId);
        sb.append(", operateType=").append(operateType);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}