package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class AcAccessCard implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_card.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_card.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_card.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_card.ac_access_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer acAccessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_card.room_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_card.access_password
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String accessPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_card.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_card.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_card.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_access_card.face_info
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String faceInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_card.id
     *
     * @return the value of ac_access_card.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_card.id
     *
     * @param id the value for ac_access_card.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_card.user_id
     *
     * @return the value of ac_access_card.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_card.user_id
     *
     * @param userId the value for ac_access_card.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_card.username
     *
     * @return the value of ac_access_card.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_card.username
     *
     * @param username the value for ac_access_card.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_card.ac_access_id
     *
     * @return the value of ac_access_card.ac_access_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getAcAccessId() {
        return acAccessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_card.ac_access_id
     *
     * @param acAccessId the value for ac_access_card.ac_access_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setAcAccessId(Integer acAccessId) {
        this.acAccessId = acAccessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_card.room_id
     *
     * @return the value of ac_access_card.room_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_card.room_id
     *
     * @param roomId the value for ac_access_card.room_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_card.access_password
     *
     * @return the value of ac_access_card.access_password
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getAccessPassword() {
        return accessPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_card.access_password
     *
     * @param accessPassword the value for ac_access_card.access_password
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setAccessPassword(String accessPassword) {
        this.accessPassword = accessPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_card.status
     *
     * @return the value of ac_access_card.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_card.status
     *
     * @param status the value for ac_access_card.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_card.create_time
     *
     * @return the value of ac_access_card.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_card.create_time
     *
     * @param createTime the value for ac_access_card.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_card.modify_time
     *
     * @return the value of ac_access_card.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_card.modify_time
     *
     * @param modifyTime the value for ac_access_card.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_access_card.face_info
     *
     * @return the value of ac_access_card.face_info
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getFaceInfo() {
        return faceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_access_card.face_info
     *
     * @param faceInfo the value for ac_access_card.face_info
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setFaceInfo(String faceInfo) {
        this.faceInfo = faceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", username=").append(username);
        sb.append(", acAccessId=").append(acAccessId);
        sb.append(", roomId=").append(roomId);
        sb.append(", accessPassword=").append(accessPassword);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", faceInfo=").append(faceInfo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}