package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class AcBuilding implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_building.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_building.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_building.eng_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String engName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_building.telephone
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_building.email
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_building.address
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_building.postcode
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_building.owner
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_building.floor_sum
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer floorSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_building.room_sum
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer roomSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_building.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_building.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_building.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_building
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_building.id
     *
     * @return the value of ac_building.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_building.id
     *
     * @param id the value for ac_building.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_building.name
     *
     * @return the value of ac_building.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_building.name
     *
     * @param name the value for ac_building.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_building.eng_name
     *
     * @return the value of ac_building.eng_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getEngName() {
        return engName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_building.eng_name
     *
     * @param engName the value for ac_building.eng_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setEngName(String engName) {
        this.engName = engName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_building.telephone
     *
     * @return the value of ac_building.telephone
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_building.telephone
     *
     * @param telephone the value for ac_building.telephone
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_building.email
     *
     * @return the value of ac_building.email
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_building.email
     *
     * @param email the value for ac_building.email
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_building.address
     *
     * @return the value of ac_building.address
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_building.address
     *
     * @param address the value for ac_building.address
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_building.postcode
     *
     * @return the value of ac_building.postcode
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_building.postcode
     *
     * @param postcode the value for ac_building.postcode
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_building.owner
     *
     * @return the value of ac_building.owner
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_building.owner
     *
     * @param owner the value for ac_building.owner
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_building.floor_sum
     *
     * @return the value of ac_building.floor_sum
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getFloorSum() {
        return floorSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_building.floor_sum
     *
     * @param floorSum the value for ac_building.floor_sum
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setFloorSum(Integer floorSum) {
        this.floorSum = floorSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_building.room_sum
     *
     * @return the value of ac_building.room_sum
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getRoomSum() {
        return roomSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_building.room_sum
     *
     * @param roomSum the value for ac_building.room_sum
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRoomSum(Integer roomSum) {
        this.roomSum = roomSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_building.status
     *
     * @return the value of ac_building.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_building.status
     *
     * @param status the value for ac_building.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_building.create_time
     *
     * @return the value of ac_building.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_building.create_time
     *
     * @param createTime the value for ac_building.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_building.modify_time
     *
     * @return the value of ac_building.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_building.modify_time
     *
     * @param modifyTime the value for ac_building.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_building
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", engName=").append(engName);
        sb.append(", telephone=").append(telephone);
        sb.append(", email=").append(email);
        sb.append(", address=").append(address);
        sb.append(", postcode=").append(postcode);
        sb.append(", owner=").append(owner);
        sb.append(", floorSum=").append(floorSum);
        sb.append(", roomSum=").append(roomSum);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}