package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class AcContract implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.c_unicode
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String cUnicode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.room_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.fee_status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte feeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.fee_order_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer feeOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.is_transfer
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte isTransfer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.pre_tenant
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String preTenant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.is_renew
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte isRenew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.pre_contract_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer preContractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_contract.contract_file_url
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String contractFileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.id
     *
     * @return the value of ac_contract.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.id
     *
     * @param id the value for ac_contract.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.c_unicode
     *
     * @return the value of ac_contract.c_unicode
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getcUnicode() {
        return cUnicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.c_unicode
     *
     * @param cUnicode the value for ac_contract.c_unicode
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setcUnicode(String cUnicode) {
        this.cUnicode = cUnicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.room_id
     *
     * @return the value of ac_contract.room_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.room_id
     *
     * @param roomId the value for ac_contract.room_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.user_id
     *
     * @return the value of ac_contract.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.user_id
     *
     * @param userId the value for ac_contract.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.username
     *
     * @return the value of ac_contract.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.username
     *
     * @param username the value for ac_contract.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.fee_status
     *
     * @return the value of ac_contract.fee_status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getFeeStatus() {
        return feeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.fee_status
     *
     * @param feeStatus the value for ac_contract.fee_status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setFeeStatus(Byte feeStatus) {
        this.feeStatus = feeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.fee_order_id
     *
     * @return the value of ac_contract.fee_order_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getFeeOrderId() {
        return feeOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.fee_order_id
     *
     * @param feeOrderId the value for ac_contract.fee_order_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setFeeOrderId(Integer feeOrderId) {
        this.feeOrderId = feeOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.is_transfer
     *
     * @return the value of ac_contract.is_transfer
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getIsTransfer() {
        return isTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.is_transfer
     *
     * @param isTransfer the value for ac_contract.is_transfer
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setIsTransfer(Byte isTransfer) {
        this.isTransfer = isTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.pre_tenant
     *
     * @return the value of ac_contract.pre_tenant
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getPreTenant() {
        return preTenant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.pre_tenant
     *
     * @param preTenant the value for ac_contract.pre_tenant
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setPreTenant(String preTenant) {
        this.preTenant = preTenant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.is_renew
     *
     * @return the value of ac_contract.is_renew
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getIsRenew() {
        return isRenew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.is_renew
     *
     * @param isRenew the value for ac_contract.is_renew
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setIsRenew(Byte isRenew) {
        this.isRenew = isRenew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.pre_contract_id
     *
     * @return the value of ac_contract.pre_contract_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getPreContractId() {
        return preContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.pre_contract_id
     *
     * @param preContractId the value for ac_contract.pre_contract_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setPreContractId(Integer preContractId) {
        this.preContractId = preContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.status
     *
     * @return the value of ac_contract.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.status
     *
     * @param status the value for ac_contract.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.create_time
     *
     * @return the value of ac_contract.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.create_time
     *
     * @param createTime the value for ac_contract.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.modify_time
     *
     * @return the value of ac_contract.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.modify_time
     *
     * @param modifyTime the value for ac_contract.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_contract.contract_file_url
     *
     * @return the value of ac_contract.contract_file_url
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getContractFileUrl() {
        return contractFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_contract.contract_file_url
     *
     * @param contractFileUrl the value for ac_contract.contract_file_url
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setContractFileUrl(String contractFileUrl) {
        this.contractFileUrl = contractFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cUnicode=").append(cUnicode);
        sb.append(", roomId=").append(roomId);
        sb.append(", userId=").append(userId);
        sb.append(", username=").append(username);
        sb.append(", feeStatus=").append(feeStatus);
        sb.append(", feeOrderId=").append(feeOrderId);
        sb.append(", isTransfer=").append(isTransfer);
        sb.append(", preTenant=").append(preTenant);
        sb.append(", isRenew=").append(isRenew);
        sb.append(", preContractId=").append(preContractId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", contractFileUrl=").append(contractFileUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}