package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class AcDepositAndWithdrawal implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_deposit_and_withdrawal.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_deposit_and_withdrawal.wallet_card_link_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer walletCardLinkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_deposit_and_withdrawal.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_deposit_and_withdrawal.type
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_deposit_and_withdrawal.money
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_deposit_and_withdrawal.security_code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String securityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_deposit_and_withdrawal.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_deposit_and_withdrawal
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_deposit_and_withdrawal.id
     *
     * @return the value of ac_deposit_and_withdrawal.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_deposit_and_withdrawal.id
     *
     * @param id the value for ac_deposit_and_withdrawal.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_deposit_and_withdrawal.wallet_card_link_id
     *
     * @return the value of ac_deposit_and_withdrawal.wallet_card_link_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getWalletCardLinkId() {
        return walletCardLinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_deposit_and_withdrawal.wallet_card_link_id
     *
     * @param walletCardLinkId the value for ac_deposit_and_withdrawal.wallet_card_link_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setWalletCardLinkId(Integer walletCardLinkId) {
        this.walletCardLinkId = walletCardLinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_deposit_and_withdrawal.username
     *
     * @return the value of ac_deposit_and_withdrawal.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_deposit_and_withdrawal.username
     *
     * @param username the value for ac_deposit_and_withdrawal.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_deposit_and_withdrawal.type
     *
     * @return the value of ac_deposit_and_withdrawal.type
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_deposit_and_withdrawal.type
     *
     * @param type the value for ac_deposit_and_withdrawal.type
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_deposit_and_withdrawal.money
     *
     * @return the value of ac_deposit_and_withdrawal.money
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_deposit_and_withdrawal.money
     *
     * @param money the value for ac_deposit_and_withdrawal.money
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_deposit_and_withdrawal.security_code
     *
     * @return the value of ac_deposit_and_withdrawal.security_code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getSecurityCode() {
        return securityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_deposit_and_withdrawal.security_code
     *
     * @param securityCode the value for ac_deposit_and_withdrawal.security_code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_deposit_and_withdrawal.create_time
     *
     * @return the value of ac_deposit_and_withdrawal.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_deposit_and_withdrawal.create_time
     *
     * @param createTime the value for ac_deposit_and_withdrawal.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_deposit_and_withdrawal
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", walletCardLinkId=").append(walletCardLinkId);
        sb.append(", username=").append(username);
        sb.append(", type=").append(type);
        sb.append(", money=").append(money);
        sb.append(", securityCode=").append(securityCode);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}