package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class AcExpress implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.track_number
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String trackNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.express_company
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String expressCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.sender
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.sender_address
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String senderAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.sender_mobile_phone
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String senderMobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.sender_mail
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String senderMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.recipient
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String recipient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.recipient_address
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String recipientAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.recipient_mobile_phone
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String recipientMobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.recipient_mail
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String recipientMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.signer
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String signer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.signer_contact
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String signerContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.send_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.arrive_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date arriveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.sign_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date signTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.express_fee
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer expressFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.is_paid
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte isPaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_express.express_records
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String expressRecords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_express
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.id
     *
     * @return the value of ac_express.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.id
     *
     * @param id the value for ac_express.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.track_number
     *
     * @return the value of ac_express.track_number
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getTrackNumber() {
        return trackNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.track_number
     *
     * @param trackNumber the value for ac_express.track_number
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setTrackNumber(String trackNumber) {
        this.trackNumber = trackNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.express_company
     *
     * @return the value of ac_express.express_company
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getExpressCompany() {
        return expressCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.express_company
     *
     * @param expressCompany the value for ac_express.express_company
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setExpressCompany(String expressCompany) {
        this.expressCompany = expressCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.sender
     *
     * @return the value of ac_express.sender
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.sender
     *
     * @param sender the value for ac_express.sender
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setSender(String sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.sender_address
     *
     * @return the value of ac_express.sender_address
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getSenderAddress() {
        return senderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.sender_address
     *
     * @param senderAddress the value for ac_express.sender_address
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setSenderAddress(String senderAddress) {
        this.senderAddress = senderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.sender_mobile_phone
     *
     * @return the value of ac_express.sender_mobile_phone
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getSenderMobilePhone() {
        return senderMobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.sender_mobile_phone
     *
     * @param senderMobilePhone the value for ac_express.sender_mobile_phone
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setSenderMobilePhone(String senderMobilePhone) {
        this.senderMobilePhone = senderMobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.sender_mail
     *
     * @return the value of ac_express.sender_mail
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getSenderMail() {
        return senderMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.sender_mail
     *
     * @param senderMail the value for ac_express.sender_mail
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setSenderMail(String senderMail) {
        this.senderMail = senderMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.recipient
     *
     * @return the value of ac_express.recipient
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getRecipient() {
        return recipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.recipient
     *
     * @param recipient the value for ac_express.recipient
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRecipient(String recipient) {
        this.recipient = recipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.recipient_address
     *
     * @return the value of ac_express.recipient_address
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getRecipientAddress() {
        return recipientAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.recipient_address
     *
     * @param recipientAddress the value for ac_express.recipient_address
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRecipientAddress(String recipientAddress) {
        this.recipientAddress = recipientAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.recipient_mobile_phone
     *
     * @return the value of ac_express.recipient_mobile_phone
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getRecipientMobilePhone() {
        return recipientMobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.recipient_mobile_phone
     *
     * @param recipientMobilePhone the value for ac_express.recipient_mobile_phone
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRecipientMobilePhone(String recipientMobilePhone) {
        this.recipientMobilePhone = recipientMobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.recipient_mail
     *
     * @return the value of ac_express.recipient_mail
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getRecipientMail() {
        return recipientMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.recipient_mail
     *
     * @param recipientMail the value for ac_express.recipient_mail
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRecipientMail(String recipientMail) {
        this.recipientMail = recipientMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.signer
     *
     * @return the value of ac_express.signer
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getSigner() {
        return signer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.signer
     *
     * @param signer the value for ac_express.signer
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setSigner(String signer) {
        this.signer = signer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.signer_contact
     *
     * @return the value of ac_express.signer_contact
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getSignerContact() {
        return signerContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.signer_contact
     *
     * @param signerContact the value for ac_express.signer_contact
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setSignerContact(String signerContact) {
        this.signerContact = signerContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.send_time
     *
     * @return the value of ac_express.send_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.send_time
     *
     * @param sendTime the value for ac_express.send_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.arrive_time
     *
     * @return the value of ac_express.arrive_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getArriveTime() {
        return arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.arrive_time
     *
     * @param arriveTime the value for ac_express.arrive_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setArriveTime(Date arriveTime) {
        this.arriveTime = arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.sign_time
     *
     * @return the value of ac_express.sign_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.sign_time
     *
     * @param signTime the value for ac_express.sign_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.express_fee
     *
     * @return the value of ac_express.express_fee
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getExpressFee() {
        return expressFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.express_fee
     *
     * @param expressFee the value for ac_express.express_fee
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setExpressFee(Integer expressFee) {
        this.expressFee = expressFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.is_paid
     *
     * @return the value of ac_express.is_paid
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getIsPaid() {
        return isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.is_paid
     *
     * @param isPaid the value for ac_express.is_paid
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setIsPaid(Byte isPaid) {
        this.isPaid = isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.status
     *
     * @return the value of ac_express.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.status
     *
     * @param status the value for ac_express.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.create_time
     *
     * @return the value of ac_express.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.create_time
     *
     * @param createTime the value for ac_express.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_express.express_records
     *
     * @return the value of ac_express.express_records
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getExpressRecords() {
        return expressRecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_express.express_records
     *
     * @param expressRecords the value for ac_express.express_records
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setExpressRecords(String expressRecords) {
        this.expressRecords = expressRecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_express
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", trackNumber=").append(trackNumber);
        sb.append(", expressCompany=").append(expressCompany);
        sb.append(", sender=").append(sender);
        sb.append(", senderAddress=").append(senderAddress);
        sb.append(", senderMobilePhone=").append(senderMobilePhone);
        sb.append(", senderMail=").append(senderMail);
        sb.append(", recipient=").append(recipient);
        sb.append(", recipientAddress=").append(recipientAddress);
        sb.append(", recipientMobilePhone=").append(recipientMobilePhone);
        sb.append(", recipientMail=").append(recipientMail);
        sb.append(", signer=").append(signer);
        sb.append(", signerContact=").append(signerContact);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", arriveTime=").append(arriveTime);
        sb.append(", signTime=").append(signTime);
        sb.append(", expressFee=").append(expressFee);
        sb.append(", isPaid=").append(isPaid);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", expressRecords=").append(expressRecords);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}