package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class AcFeeOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_fee_order.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_fee_order.room_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_fee_order.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_fee_order.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_fee_order.order_title
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String orderTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_fee_order.amounts_payable
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer amountsPayable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_fee_order.arrears
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer arrears;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_fee_order.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_fee_order.deadline
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_fee_order.payment_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date paymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_fee_order.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_fee_order.order_detail
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String orderDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_fee_order.order_flow_records
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String orderFlowRecords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_fee_order.id
     *
     * @return the value of ac_fee_order.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_fee_order.id
     *
     * @param id the value for ac_fee_order.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_fee_order.room_id
     *
     * @return the value of ac_fee_order.room_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_fee_order.room_id
     *
     * @param roomId the value for ac_fee_order.room_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_fee_order.user_id
     *
     * @return the value of ac_fee_order.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_fee_order.user_id
     *
     * @param userId the value for ac_fee_order.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_fee_order.username
     *
     * @return the value of ac_fee_order.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_fee_order.username
     *
     * @param username the value for ac_fee_order.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_fee_order.order_title
     *
     * @return the value of ac_fee_order.order_title
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getOrderTitle() {
        return orderTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_fee_order.order_title
     *
     * @param orderTitle the value for ac_fee_order.order_title
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setOrderTitle(String orderTitle) {
        this.orderTitle = orderTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_fee_order.amounts_payable
     *
     * @return the value of ac_fee_order.amounts_payable
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getAmountsPayable() {
        return amountsPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_fee_order.amounts_payable
     *
     * @param amountsPayable the value for ac_fee_order.amounts_payable
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setAmountsPayable(Integer amountsPayable) {
        this.amountsPayable = amountsPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_fee_order.arrears
     *
     * @return the value of ac_fee_order.arrears
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getArrears() {
        return arrears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_fee_order.arrears
     *
     * @param arrears the value for ac_fee_order.arrears
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setArrears(Integer arrears) {
        this.arrears = arrears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_fee_order.status
     *
     * @return the value of ac_fee_order.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_fee_order.status
     *
     * @param status the value for ac_fee_order.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_fee_order.deadline
     *
     * @return the value of ac_fee_order.deadline
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_fee_order.deadline
     *
     * @param deadline the value for ac_fee_order.deadline
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_fee_order.payment_time
     *
     * @return the value of ac_fee_order.payment_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_fee_order.payment_time
     *
     * @param paymentTime the value for ac_fee_order.payment_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_fee_order.create_time
     *
     * @return the value of ac_fee_order.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_fee_order.create_time
     *
     * @param createTime the value for ac_fee_order.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_fee_order.order_detail
     *
     * @return the value of ac_fee_order.order_detail
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getOrderDetail() {
        return orderDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_fee_order.order_detail
     *
     * @param orderDetail the value for ac_fee_order.order_detail
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setOrderDetail(String orderDetail) {
        this.orderDetail = orderDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_fee_order.order_flow_records
     *
     * @return the value of ac_fee_order.order_flow_records
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getOrderFlowRecords() {
        return orderFlowRecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_fee_order.order_flow_records
     *
     * @param orderFlowRecords the value for ac_fee_order.order_flow_records
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setOrderFlowRecords(String orderFlowRecords) {
        this.orderFlowRecords = orderFlowRecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roomId=").append(roomId);
        sb.append(", userId=").append(userId);
        sb.append(", username=").append(username);
        sb.append(", orderTitle=").append(orderTitle);
        sb.append(", amountsPayable=").append(amountsPayable);
        sb.append(", arrears=").append(arrears);
        sb.append(", status=").append(status);
        sb.append(", deadline=").append(deadline);
        sb.append(", paymentTime=").append(paymentTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", orderDetail=").append(orderDetail);
        sb.append(", orderFlowRecords=").append(orderFlowRecords);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}