package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class AcRoomAccessControl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_room_access_control.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_room_access_control.room_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_room_access_control.ac_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer acId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_room_access_control.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_room_access_control.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_room_access_control.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_room_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_room_access_control.id
     *
     * @return the value of ac_room_access_control.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_room_access_control.id
     *
     * @param id the value for ac_room_access_control.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_room_access_control.room_id
     *
     * @return the value of ac_room_access_control.room_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_room_access_control.room_id
     *
     * @param roomId the value for ac_room_access_control.room_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_room_access_control.ac_id
     *
     * @return the value of ac_room_access_control.ac_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getAcId() {
        return acId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_room_access_control.ac_id
     *
     * @param acId the value for ac_room_access_control.ac_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setAcId(Integer acId) {
        this.acId = acId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_room_access_control.status
     *
     * @return the value of ac_room_access_control.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_room_access_control.status
     *
     * @param status the value for ac_room_access_control.status
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_room_access_control.create_time
     *
     * @return the value of ac_room_access_control.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_room_access_control.create_time
     *
     * @param createTime the value for ac_room_access_control.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_room_access_control.modify_time
     *
     * @return the value of ac_room_access_control.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_room_access_control.modify_time
     *
     * @param modifyTime the value for ac_room_access_control.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roomId=").append(roomId);
        sb.append(", acId=").append(acId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}