package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class AcTransaction implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.transaction_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.trans_detail
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String transDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.trans_property
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte transProperty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.fee_type
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Byte feeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.payment_channel
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String paymentChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.trans_amount
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer transAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.payer_account
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String payerAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.payer_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String payerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.payer_institution
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String payerInstitution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.recipient_account
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String recipientAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.recipient_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String recipientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.recipient_institution
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String recipientInstitution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_transaction.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_transaction
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.id
     *
     * @return the value of ac_transaction.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.id
     *
     * @param id the value for ac_transaction.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.transaction_id
     *
     * @return the value of ac_transaction.transaction_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.transaction_id
     *
     * @param transactionId the value for ac_transaction.transaction_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.user_id
     *
     * @return the value of ac_transaction.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.user_id
     *
     * @param userId the value for ac_transaction.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.username
     *
     * @return the value of ac_transaction.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.username
     *
     * @param username the value for ac_transaction.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.trans_detail
     *
     * @return the value of ac_transaction.trans_detail
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getTransDetail() {
        return transDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.trans_detail
     *
     * @param transDetail the value for ac_transaction.trans_detail
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setTransDetail(String transDetail) {
        this.transDetail = transDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.trans_property
     *
     * @return the value of ac_transaction.trans_property
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getTransProperty() {
        return transProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.trans_property
     *
     * @param transProperty the value for ac_transaction.trans_property
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setTransProperty(Byte transProperty) {
        this.transProperty = transProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.fee_type
     *
     * @return the value of ac_transaction.fee_type
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Byte getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.fee_type
     *
     * @param feeType the value for ac_transaction.fee_type
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setFeeType(Byte feeType) {
        this.feeType = feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.payment_channel
     *
     * @return the value of ac_transaction.payment_channel
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getPaymentChannel() {
        return paymentChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.payment_channel
     *
     * @param paymentChannel the value for ac_transaction.payment_channel
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setPaymentChannel(String paymentChannel) {
        this.paymentChannel = paymentChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.trans_amount
     *
     * @return the value of ac_transaction.trans_amount
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getTransAmount() {
        return transAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.trans_amount
     *
     * @param transAmount the value for ac_transaction.trans_amount
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setTransAmount(Integer transAmount) {
        this.transAmount = transAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.payer_account
     *
     * @return the value of ac_transaction.payer_account
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getPayerAccount() {
        return payerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.payer_account
     *
     * @param payerAccount the value for ac_transaction.payer_account
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setPayerAccount(String payerAccount) {
        this.payerAccount = payerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.payer_name
     *
     * @return the value of ac_transaction.payer_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.payer_name
     *
     * @param payerName the value for ac_transaction.payer_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.payer_institution
     *
     * @return the value of ac_transaction.payer_institution
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getPayerInstitution() {
        return payerInstitution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.payer_institution
     *
     * @param payerInstitution the value for ac_transaction.payer_institution
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setPayerInstitution(String payerInstitution) {
        this.payerInstitution = payerInstitution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.recipient_account
     *
     * @return the value of ac_transaction.recipient_account
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getRecipientAccount() {
        return recipientAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.recipient_account
     *
     * @param recipientAccount the value for ac_transaction.recipient_account
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRecipientAccount(String recipientAccount) {
        this.recipientAccount = recipientAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.recipient_name
     *
     * @return the value of ac_transaction.recipient_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getRecipientName() {
        return recipientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.recipient_name
     *
     * @param recipientName the value for ac_transaction.recipient_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRecipientName(String recipientName) {
        this.recipientName = recipientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.recipient_institution
     *
     * @return the value of ac_transaction.recipient_institution
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getRecipientInstitution() {
        return recipientInstitution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.recipient_institution
     *
     * @param recipientInstitution the value for ac_transaction.recipient_institution
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRecipientInstitution(String recipientInstitution) {
        this.recipientInstitution = recipientInstitution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_transaction.create_time
     *
     * @return the value of ac_transaction.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_transaction.create_time
     *
     * @param createTime the value for ac_transaction.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_transaction
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", transactionId=").append(transactionId);
        sb.append(", userId=").append(userId);
        sb.append(", username=").append(username);
        sb.append(", transDetail=").append(transDetail);
        sb.append(", transProperty=").append(transProperty);
        sb.append(", feeType=").append(feeType);
        sb.append(", paymentChannel=").append(paymentChannel);
        sb.append(", transAmount=").append(transAmount);
        sb.append(", payerAccount=").append(payerAccount);
        sb.append(", payerName=").append(payerName);
        sb.append(", payerInstitution=").append(payerInstitution);
        sb.append(", recipientAccount=").append(recipientAccount);
        sb.append(", recipientName=").append(recipientName);
        sb.append(", recipientInstitution=").append(recipientInstitution);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}