package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class AcWallet implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet.balance
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_wallet
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet.id
     *
     * @return the value of ac_wallet.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet.id
     *
     * @param id the value for ac_wallet.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet.user_id
     *
     * @return the value of ac_wallet.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet.user_id
     *
     * @param userId the value for ac_wallet.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet.username
     *
     * @return the value of ac_wallet.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet.username
     *
     * @param username the value for ac_wallet.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet.balance
     *
     * @return the value of ac_wallet.balance
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet.balance
     *
     * @param balance the value for ac_wallet.balance
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet.create_time
     *
     * @return the value of ac_wallet.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet.create_time
     *
     * @param createTime the value for ac_wallet.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet.modify_time
     *
     * @return the value of ac_wallet.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet.modify_time
     *
     * @param modifyTime the value for ac_wallet.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", username=").append(username);
        sb.append(", balance=").append(balance);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}