package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class AcWalletCardLink implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet_card_link.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet_card_link.wallet_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer walletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet_card_link.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet_card_link.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet_card_link.card_number
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String cardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet_card_link.security_code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String securityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet_card_link.bank
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet_card_link.card_owner_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String cardOwnerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet_card_link.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_wallet_card_link.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_wallet_card_link
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet_card_link.id
     *
     * @return the value of ac_wallet_card_link.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet_card_link.id
     *
     * @param id the value for ac_wallet_card_link.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet_card_link.wallet_id
     *
     * @return the value of ac_wallet_card_link.wallet_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet_card_link.wallet_id
     *
     * @param walletId the value for ac_wallet_card_link.wallet_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setWalletId(Integer walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet_card_link.user_id
     *
     * @return the value of ac_wallet_card_link.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet_card_link.user_id
     *
     * @param userId the value for ac_wallet_card_link.user_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet_card_link.username
     *
     * @return the value of ac_wallet_card_link.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet_card_link.username
     *
     * @param username the value for ac_wallet_card_link.username
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet_card_link.card_number
     *
     * @return the value of ac_wallet_card_link.card_number
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet_card_link.card_number
     *
     * @param cardNumber the value for ac_wallet_card_link.card_number
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet_card_link.security_code
     *
     * @return the value of ac_wallet_card_link.security_code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getSecurityCode() {
        return securityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet_card_link.security_code
     *
     * @param securityCode the value for ac_wallet_card_link.security_code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet_card_link.bank
     *
     * @return the value of ac_wallet_card_link.bank
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet_card_link.bank
     *
     * @param bank the value for ac_wallet_card_link.bank
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setBank(String bank) {
        this.bank = bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet_card_link.card_owner_name
     *
     * @return the value of ac_wallet_card_link.card_owner_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getCardOwnerName() {
        return cardOwnerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet_card_link.card_owner_name
     *
     * @param cardOwnerName the value for ac_wallet_card_link.card_owner_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCardOwnerName(String cardOwnerName) {
        this.cardOwnerName = cardOwnerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet_card_link.create_time
     *
     * @return the value of ac_wallet_card_link.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet_card_link.create_time
     *
     * @param createTime the value for ac_wallet_card_link.create_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_wallet_card_link.modify_time
     *
     * @return the value of ac_wallet_card_link.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_wallet_card_link.modify_time
     *
     * @param modifyTime the value for ac_wallet_card_link.modify_time
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet_card_link
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", walletId=").append(walletId);
        sb.append(", userId=").append(userId);
        sb.append(", username=").append(username);
        sb.append(", cardNumber=").append(cardNumber);
        sb.append(", securityCode=").append(securityCode);
        sb.append(", bank=").append(bank);
        sb.append(", cardOwnerName=").append(cardOwnerName);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}