package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;

public class LocArea implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_area.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_area.country_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer countryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_area.code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_area.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_area.cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_area.lower_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String lowerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loc_area
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_area.id
     *
     * @return the value of loc_area.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_area.id
     *
     * @param id the value for loc_area.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_area.country_id
     *
     * @return the value of loc_area.country_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_area.country_id
     *
     * @param countryId the value for loc_area.country_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_area.code
     *
     * @return the value of loc_area.code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_area.code
     *
     * @param code the value for loc_area.code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_area.name
     *
     * @return the value of loc_area.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_area.name
     *
     * @param name the value for loc_area.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_area.cname
     *
     * @return the value of loc_area.cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_area.cname
     *
     * @param cname the value for loc_area.cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_area.lower_name
     *
     * @return the value of loc_area.lower_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getLowerName() {
        return lowerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_area.lower_name
     *
     * @param lowerName the value for loc_area.lower_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setLowerName(String lowerName) {
        this.lowerName = lowerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_area
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", countryId=").append(countryId);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", cname=").append(cname);
        sb.append(", lowerName=").append(lowerName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}