package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;

public class LocCountries implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_countries.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_countries.continent_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer continentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_countries.code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_countries.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_countries.full_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_countries.cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_countries.full_cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String fullCname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_countries.lower_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String lowerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_countries.remark
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_countries.id
     *
     * @return the value of loc_countries.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_countries.id
     *
     * @param id the value for loc_countries.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_countries.continent_id
     *
     * @return the value of loc_countries.continent_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getContinentId() {
        return continentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_countries.continent_id
     *
     * @param continentId the value for loc_countries.continent_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setContinentId(Integer continentId) {
        this.continentId = continentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_countries.code
     *
     * @return the value of loc_countries.code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_countries.code
     *
     * @param code the value for loc_countries.code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_countries.name
     *
     * @return the value of loc_countries.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_countries.name
     *
     * @param name the value for loc_countries.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_countries.full_name
     *
     * @return the value of loc_countries.full_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_countries.full_name
     *
     * @param fullName the value for loc_countries.full_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_countries.cname
     *
     * @return the value of loc_countries.cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_countries.cname
     *
     * @param cname the value for loc_countries.cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_countries.full_cname
     *
     * @return the value of loc_countries.full_cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getFullCname() {
        return fullCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_countries.full_cname
     *
     * @param fullCname the value for loc_countries.full_cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setFullCname(String fullCname) {
        this.fullCname = fullCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_countries.lower_name
     *
     * @return the value of loc_countries.lower_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getLowerName() {
        return lowerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_countries.lower_name
     *
     * @param lowerName the value for loc_countries.lower_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setLowerName(String lowerName) {
        this.lowerName = lowerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_countries.remark
     *
     * @return the value of loc_countries.remark
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_countries.remark
     *
     * @param remark the value for loc_countries.remark
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", continentId=").append(continentId);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", fullName=").append(fullName);
        sb.append(", cname=").append(cname);
        sb.append(", fullCname=").append(fullCname);
        sb.append(", lowerName=").append(lowerName);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}