package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;

public class LocContinents implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_continents.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_continents.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_continents.cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_continents.lower_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String lowerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loc_continents
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_continents.id
     *
     * @return the value of loc_continents.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_continents.id
     *
     * @param id the value for loc_continents.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_continents.name
     *
     * @return the value of loc_continents.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_continents.name
     *
     * @param name the value for loc_continents.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_continents.cname
     *
     * @return the value of loc_continents.cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_continents.cname
     *
     * @param cname the value for loc_continents.cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_continents.lower_name
     *
     * @return the value of loc_continents.lower_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getLowerName() {
        return lowerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_continents.lower_name
     *
     * @param lowerName the value for loc_continents.lower_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setLowerName(String lowerName) {
        this.lowerName = lowerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_continents
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", cname=").append(cname);
        sb.append(", lowerName=").append(lowerName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}