package com.gbtech.iaaas.mbg.model;

import java.io.Serializable;

public class LocRegions implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_regions.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_regions.city_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private Short cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_regions.code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_regions.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_regions.cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_regions.lower_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String lowerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loc_regions.code_full
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private String codeFull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loc_regions
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_regions.id
     *
     * @return the value of loc_regions.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_regions.id
     *
     * @param id the value for loc_regions.id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_regions.city_id
     *
     * @return the value of loc_regions.city_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public Short getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_regions.city_id
     *
     * @param cityId the value for loc_regions.city_id
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCityId(Short cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_regions.code
     *
     * @return the value of loc_regions.code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_regions.code
     *
     * @param code the value for loc_regions.code
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_regions.name
     *
     * @return the value of loc_regions.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_regions.name
     *
     * @param name the value for loc_regions.name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_regions.cname
     *
     * @return the value of loc_regions.cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_regions.cname
     *
     * @param cname the value for loc_regions.cname
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_regions.lower_name
     *
     * @return the value of loc_regions.lower_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getLowerName() {
        return lowerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_regions.lower_name
     *
     * @param lowerName the value for loc_regions.lower_name
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setLowerName(String lowerName) {
        this.lowerName = lowerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loc_regions.code_full
     *
     * @return the value of loc_regions.code_full
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public String getCodeFull() {
        return codeFull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loc_regions.code_full
     *
     * @param codeFull the value for loc_regions.code_full
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    public void setCodeFull(String codeFull) {
        this.codeFull = codeFull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_regions
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cityId=").append(cityId);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", cname=").append(cname);
        sb.append(", lowerName=").append(lowerName);
        sb.append(", codeFull=").append(codeFull);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}