server:
  port:8999

spring:
  datasource:
    url:jdbc:mysql://localhost:3306/iaaas?serverTimezone=GMT%2B8
    username:root
    password:Test@1234

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml