server:
  port: 8999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iaaas?serverTimezone=GMT%2B8
    username: root
    password: Test@1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


jwt:
  tokenHeader: Authorization # JWT存储的请求头
  secret: iaaasSecret # JWT加解密使用的密钥
  expiration: 604800 # JWT的超期限时间(60*60*24)
  tokenHead: Bearer  # JWT负载中拿到开头