package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.AcAccessRecord;
import com.gbtech.iaaas.mbg.model.AcAccessRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcAccessRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_record
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(AcAccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_record
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(AcAccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_record
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_record
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(AcAccessRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_record
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(AcAccessRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_record
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcAccessRecord> selectByExample(AcAccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_record
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    AcAccessRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_record
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") AcAccessRecord row, @Param("example") AcAccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_record
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") AcAccessRecord row, @Param("example") AcAccessRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_record
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(AcAccessRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_record
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(AcAccessRecord row);
}