package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.AcAccessCard;
import com.gbtech.iaaas.mbg.model.AcAccessCardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcAccessCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(AcAccessCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(AcAccessCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(AcAccessCard row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(AcAccessCard row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcAccessCard> selectByExampleWithBLOBs(AcAccessCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcAccessCard> selectByExample(AcAccessCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    AcAccessCard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") AcAccessCard row, @Param("example") AcAccessCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") AcAccessCard row, @Param("example") AcAccessCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") AcAccessCard row, @Param("example") AcAccessCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(AcAccessCard row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeyWithBLOBs(AcAccessCard row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_access_card
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(AcAccessCard row);
}