package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.AcBuilding;
import com.gbtech.iaaas.mbg.model.AcBuildingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcBuildingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_building
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(AcBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_building
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(AcBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_building
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_building
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(AcBuilding row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_building
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(AcBuilding row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_building
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcBuilding> selectByExample(AcBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_building
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    AcBuilding selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_building
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") AcBuilding row, @Param("example") AcBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_building
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") AcBuilding row, @Param("example") AcBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_building
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(AcBuilding row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_building
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(AcBuilding row);
}