package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.AcContract;
import com.gbtech.iaaas.mbg.model.AcContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(AcContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(AcContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(AcContract row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(AcContract row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcContract> selectByExampleWithBLOBs(AcContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcContract> selectByExample(AcContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    AcContract selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") AcContract row, @Param("example") AcContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") AcContract row, @Param("example") AcContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") AcContract row, @Param("example") AcContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(AcContract row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeyWithBLOBs(AcContract row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_contract
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(AcContract row);
}