package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.AcDepositAndWithdrawal;
import com.gbtech.iaaas.mbg.model.AcDepositAndWithdrawalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcDepositAndWithdrawalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_deposit_and_withdrawal
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(AcDepositAndWithdrawalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_deposit_and_withdrawal
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(AcDepositAndWithdrawalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_deposit_and_withdrawal
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_deposit_and_withdrawal
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(AcDepositAndWithdrawal row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_deposit_and_withdrawal
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(AcDepositAndWithdrawal row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_deposit_and_withdrawal
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcDepositAndWithdrawal> selectByExample(AcDepositAndWithdrawalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_deposit_and_withdrawal
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    AcDepositAndWithdrawal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_deposit_and_withdrawal
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") AcDepositAndWithdrawal row, @Param("example") AcDepositAndWithdrawalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_deposit_and_withdrawal
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") AcDepositAndWithdrawal row, @Param("example") AcDepositAndWithdrawalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_deposit_and_withdrawal
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(AcDepositAndWithdrawal row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_deposit_and_withdrawal
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(AcDepositAndWithdrawal row);
}