package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.AcFeeOrder;
import com.gbtech.iaaas.mbg.model.AcFeeOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcFeeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(AcFeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(AcFeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(AcFeeOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(AcFeeOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcFeeOrder> selectByExampleWithBLOBs(AcFeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcFeeOrder> selectByExample(AcFeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    AcFeeOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") AcFeeOrder row, @Param("example") AcFeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") AcFeeOrder row, @Param("example") AcFeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") AcFeeOrder row, @Param("example") AcFeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(AcFeeOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeyWithBLOBs(AcFeeOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_fee_order
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(AcFeeOrder row);
}