package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.AcPublicAccessControl;
import com.gbtech.iaaas.mbg.model.AcPublicAccessControlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcPublicAccessControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_public_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(AcPublicAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_public_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(AcPublicAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_public_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_public_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(AcPublicAccessControl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_public_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(AcPublicAccessControl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_public_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcPublicAccessControl> selectByExample(AcPublicAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_public_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    AcPublicAccessControl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_public_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") AcPublicAccessControl row, @Param("example") AcPublicAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_public_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") AcPublicAccessControl row, @Param("example") AcPublicAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_public_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(AcPublicAccessControl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_public_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(AcPublicAccessControl row);
}