package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.AcRoomAccessControl;
import com.gbtech.iaaas.mbg.model.AcRoomAccessControlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcRoomAccessControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(AcRoomAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(AcRoomAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(AcRoomAccessControl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(AcRoomAccessControl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcRoomAccessControl> selectByExample(AcRoomAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    AcRoomAccessControl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") AcRoomAccessControl row, @Param("example") AcRoomAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") AcRoomAccessControl row, @Param("example") AcRoomAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(AcRoomAccessControl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room_access_control
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(AcRoomAccessControl row);
}