package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.AcRoom;
import com.gbtech.iaaas.mbg.model.AcRoomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(AcRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(AcRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(AcRoom row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(AcRoom row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcRoom> selectByExampleWithBLOBs(AcRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcRoom> selectByExample(AcRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    AcRoom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") AcRoom row, @Param("example") AcRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") AcRoom row, @Param("example") AcRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") AcRoom row, @Param("example") AcRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(AcRoom row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeyWithBLOBs(AcRoom row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_room
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(AcRoom row);
}