package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.AcTransaction;
import com.gbtech.iaaas.mbg.model.AcTransactionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_transaction
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(AcTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_transaction
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(AcTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_transaction
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_transaction
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(AcTransaction row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_transaction
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(AcTransaction row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_transaction
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcTransaction> selectByExample(AcTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_transaction
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    AcTransaction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_transaction
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") AcTransaction row, @Param("example") AcTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_transaction
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") AcTransaction row, @Param("example") AcTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_transaction
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(AcTransaction row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_transaction
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(AcTransaction row);
}