package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.AcWalletCardLink;
import com.gbtech.iaaas.mbg.model.AcWalletCardLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcWalletCardLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet_card_link
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(AcWalletCardLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet_card_link
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(AcWalletCardLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet_card_link
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet_card_link
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(AcWalletCardLink row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet_card_link
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(AcWalletCardLink row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet_card_link
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcWalletCardLink> selectByExample(AcWalletCardLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet_card_link
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    AcWalletCardLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet_card_link
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") AcWalletCardLink row, @Param("example") AcWalletCardLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet_card_link
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") AcWalletCardLink row, @Param("example") AcWalletCardLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet_card_link
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(AcWalletCardLink row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet_card_link
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(AcWalletCardLink row);
}