package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.AcWallet;
import com.gbtech.iaaas.mbg.model.AcWalletExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcWalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(AcWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(AcWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(AcWallet row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(AcWallet row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AcWallet> selectByExample(AcWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    AcWallet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") AcWallet row, @Param("example") AcWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") AcWallet row, @Param("example") AcWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(AcWallet row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_wallet
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(AcWallet row);
}