package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.AeUser;
import com.gbtech.iaaas.mbg.model.AeUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_user
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(AeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_user
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(AeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_user
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_user
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(AeUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_user
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(AeUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_user
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<AeUser> selectByExample(AeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_user
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    AeUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_user
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") AeUser row, @Param("example") AeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_user
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") AeUser row, @Param("example") AeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_user
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(AeUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ae_user
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(AeUser row);
}