package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.LocArea;
import com.gbtech.iaaas.mbg.model.LocAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_area
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(LocAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_area
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(LocAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_area
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_area
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(LocArea row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_area
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(LocArea row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_area
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<LocArea> selectByExample(LocAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_area
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    LocArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_area
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") LocArea row, @Param("example") LocAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_area
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") LocArea row, @Param("example") LocAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_area
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(LocArea row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_area
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(LocArea row);
}