package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.LocCountries;
import com.gbtech.iaaas.mbg.model.LocCountriesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocCountriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(LocCountriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(LocCountriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(LocCountries row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(LocCountries row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<LocCountries> selectByExampleWithBLOBs(LocCountriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<LocCountries> selectByExample(LocCountriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    LocCountries selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") LocCountries row, @Param("example") LocCountriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") LocCountries row, @Param("example") LocCountriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") LocCountries row, @Param("example") LocCountriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(LocCountries row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeyWithBLOBs(LocCountries row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_countries
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(LocCountries row);
}