package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.LocContinents;
import com.gbtech.iaaas.mbg.model.LocContinentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocContinentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_continents
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(LocContinentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_continents
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(LocContinentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_continents
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_continents
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(LocContinents row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_continents
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(LocContinents row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_continents
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<LocContinents> selectByExample(LocContinentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_continents
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    LocContinents selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_continents
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") LocContinents row, @Param("example") LocContinentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_continents
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") LocContinents row, @Param("example") LocContinentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_continents
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(LocContinents row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_continents
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(LocContinents row);
}