package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.LocCities;
import com.gbtech.iaaas.mbg.model.LocCitiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocCitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_cities
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(LocCitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_cities
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(LocCitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_cities
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_cities
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(LocCities row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_cities
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(LocCities row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_cities
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<LocCities> selectByExample(LocCitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_cities
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    LocCities selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_cities
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") LocCities row, @Param("example") LocCitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_cities
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") LocCities row, @Param("example") LocCitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_cities
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(LocCities row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_cities
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(LocCities row);
}