package com.gbtech.iaaas.mbg.mapper;

import com.gbtech.iaaas.mbg.model.LocRegions;
import com.gbtech.iaaas.mbg.model.LocRegionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocRegionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_regions
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    long countByExample(LocRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_regions
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByExample(LocRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_regions
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_regions
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insert(LocRegions row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_regions
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int insertSelective(LocRegions row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_regions
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    List<LocRegions> selectByExample(LocRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_regions
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    LocRegions selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_regions
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExampleSelective(@Param("row") LocRegions row, @Param("example") LocRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_regions
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByExample(@Param("row") LocRegions row, @Param("example") LocRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_regions
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKeySelective(LocRegions row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loc_regions
     *
     * @mbg.generated Wed May 25 07:04:03 BST 2022
     */
    int updateByPrimaryKey(LocRegions row);
}